version: "3.8"
services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: cosmos-emulator
    command: ["--protocol","https"]  # or "https-insecure"
    ports:
      - "8081:8081"   # Gateway (SDK endpoint)
      - "1234:1234"   # Data Explorer (UI)
    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    volumes:
      - cosmos_data:/data
    restart: unless-stopped
volumes:
  cosmos_data:
